# 端口号
server:
  port: 8071

#配置 freemarker
spring:
  freemarker:
    cache: false  #是否开启缓存
    charset: UTF-8  #字符集
    template-loader-path: "classpath:/templates/" #去哪里找视图
    suffix: .html #找已什么结尾的视图
