#????
server:
  port: 8098

#??Spring???freemarker
spring:
  freemarker:
    cache: false #??????
    charset: UTF-8  #?????
    template-loader-path: "classpath:/templates/" #??????
    suffix: .html #?????????

#连接数据库
  datasource:
    url: jdbc:mysql://localhost:3306/java_practice?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:/mapper/**.xml
